"""
Ground Truth models for the simulator.
"""

from typing import Dict, List
from pydantic import BaseModel

from simulator.config import SimulationConfig
from backend.app.models.merchant import Merchant
from backend.app.models.order import Order
from backend.app.models.payment import Payment
from backend.app.models.settlement_transaction import SettlementTransaction
from backend.app.models.settlement import Settlement
from backend.app.models.bank_entry import BankEntry

class ScenarioLabel(BaseModel):
    """Labels the scenario for a given settlement."""
    settlement_id: str
    scenario_type: str

class GroundTruth(BaseModel):
    """
    The complete synthetic financial world generated by the simulator.
    """
    config: SimulationConfig
    merchants: List[Merchant]
    orders: List[Order]
    payments: List[Payment]
    settlement_transactions: List[SettlementTransaction]
    settlements: List[Settlement]
    bank_entries: List[BankEntry]
    scenario_labels: Dict[str, ScenarioLabel]
